
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"ao-Articles-delete","number":69,"title":"Add DELETE endpoint for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/69"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"ao-Articles-get","number":68,"title":"Added Get endpoint for a single record for Articles Table","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/68"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequestPut","number":63,"title":"Add PUT endpoint for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/63"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequestDelete","number":62,"title":"Add DELETE for HelpRequests","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/62"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequestGet","number":61,"title":"Add GET for a single endpoint for HelpRequests","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/61"},{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-PR-In-Review","number":60,"title":"A0 - PR in Review","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/60"},{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-UCSBDiningCommonsMenuItemController","number":49,"title":"Create UCSBDiningCommonsMenuItemController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/49"}]
