
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"ao-Articles-controller","number":52,"title":"Added Article Controller with GET/POST & Tests ","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/52"},{"author":{"id":"MDQ6VXNlcjU0MTI2NTgw","is_bot":false,"login":"JonathanCheng123","name":"Jonathan Cheng"},"headRefName":"Jonathan-HelpRequestController","number":51,"title":"Add GET/POST for HelpRequests","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/51"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Ray-RecommendationRequests","number":50,"title":"Ray - add database of recommendation requests","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/50"},{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-UCSBDiningCommonsMenuItemController","number":49,"title":"Create UCSBDiningCommonsMenuItemController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/49"},{"author":{"id":"U_kgDOBXjycA","is_bot":false,"login":"huangderful","name":""},"headRefName":"rh-MenuItemReview-create-controller","number":48,"title":"rh - added controller and tests to menuitem get all and post","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-2/pull/48"}]
